apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cephfs-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ceph-csi-cephfs
---
apiVersion: v1
kind: Pod
metadata:
  name: cephfs-app
spec:
  containers:
    - name: app
      image: busybox
      command: ["/bin/sh"]
      args: ["-c", "echo 'CephFS is working!' > /mnt/test/data.txt && cat /mnt/test/data.txt && sleep 3600"]
      volumeMounts:
        - mountPath: "/mnt/test"
          name: cephfs-vol 
  volumes:
    - name: cephfs-vol
      persistentVolumeClaim:
        claimName: cephfs-pvc
